udacityalumni/udacity-alumni-fe

app/src/components/App/index.js
app/src/components/MainAside/README.md
app/src/components/MainAside/index.js
app/src/components/MainAside/index.module.scss
app/src/components/MainAside/tests/__snapshots__/index.test.js.snap
app/src/components/MainAside/tests/index.test.js
app/src/components/MainCarousel/README.md
app/src/components/MainCarousel/index.js
app/src/components/MainCarousel/index.module.scss
app/src/components/MainCarousel/tests/__snapshots__/index.test.js.snap
app/src/components/MainCarousel/tests/index.test.js
app/src/components/Navbar/README.md
app/src/components/Navbar/index.js
app/src/components/Navbar/tests/__snapshots__/index.test.js.snap
app/src/components/SpotlightArticles/README.md
app/src/components/SpotlightArticles/index.js
app/src/components/SpotlightArticles/index.module.scss
app/src/components/SpotlightArticles/tests/__snapshots__/index.test.js.snap
app/src/components/SpotlightArticles/tests/index.test.js
app/src/components/index.js
app/src/containers/LandingContainer/README.md
app/src/containers/LandingContainer/index.js
app/src/containers/LandingContainer/index.module.scss
app/src/containers/LandingContainer/reducer.js
app/src/containers/LandingContainer/tests/__snapshots__/index.test.js.snap
app/src/containers/LandingContainer/tests/reducer.test.js

Scaffolding of the main page to show what is possible with the current setup.  Please feel free to play around with the sample components to get a feel for how things work!

Feat rc scaffolding

---

app/src/components/Navbar/index.js
app/src/components/Navbar/index.module.scss

Add styling to make the navbar more realistic and responsive

Fix rc navbar styling

---

app/src/components/App/index.js
app/src/components/MainAside/index.module.scss
app/src/components/MainCarousel/index.js
app/src/components/MainCarousel/index.module.scss
app/src/components/Navbar/index.js
app/src/containers/LandingContainer/index.js
app/src/containers/LoginContainer/index.js
app/styles/styles.scss
package.json
webpack.config.babel.js

- Add custom SCSS for udacity theme
- Update components with new theme

Feat rc import grommet scss

---

.all-contributorsrc
README.md
package.json

Add contributors to readme and a script to update contributors

Feat rc all contributors

---

how_to_get_started.md

I wrote a small Beginner's Guide to make it easier for new people to get started.
Should this be put elsewhere (e.g. in the Wiki, and linked from the README.md)?
I'm also practicing to walk the walk of the proper workflow, so I hope that's fine and that I did my messages well ; )

Docs: add beginner's guide

---

app/src/components/App/actions.js
app/src/components/App/constants.js
app/src/components/App/index.js
app/src/components/App/reducer.js
app/src/components/AppHeader/README.md
app/src/components/AppHeader/index.js
app/src/components/AppHeader/index.module.scss
app/src/components/AppHeader/tests/index.test.js
app/src/components/CmsEditor/tests/__snapshots__/index.test.js.snap
app/src/components/CmsToolbar/index.js
app/src/components/CmsToolbar/tests/__snapshots__/index.test.js.snap
app/src/components/MobileNav/README.md
app/src/components/MobileNav/index.js
app/src/components/MobileNav/index.module.scss
app/src/components/MobileNav/tests/__snapshots__/index.test.js.snap
app/src/components/MobileNav/tests/index.test.js
app/src/components/SessionMenu/README.md
app/src/components/SessionMenu/index.js
app/src/components/SessionMenu/index.module.scss
app/src/components/SessionMenu/tests/__snapshots__/index.test.js.snap
app/src/components/SessionMenu/tests/index.test.js
app/src/components/index.js
app/src/reducers.js
app/src/store.js
app/styles/styles.scss
app/utils/a11y.js
package.json
webpack.config.babel.js

- Add mobile navigation to app component
- App component now has some state, so would like to refactor so that auth state is handled in the App component

Feat rc add mobile nav

---

how_to_build_a_page.md

This is a work in progress of me re-doing the SinglePageApp demo (and some).
I'm trying to write it as a beginner's guide to follow-along, also showing some of the issues (and eventually solutions) one might encounter. Well, those that I did encounter or wonder about.
It's late and I'll go to bed soon. More on this will come soon! : )

add beginner's guide to creating a page

---

app/src/components/ArticlePreview/index.js
app/src/components/ArticlePreview/utils/index.js
app/src/containers/SearchContainer/index.js

I implemented a very simple algorythm to highlight the search terms. It still doesn't work for bigger texts because we have to show the right snippet containing the search term in the preview.
Will take care of that soon.

Feat search highlight

---

app/src/components/AppFooter/index.js
app/src/components/AppFooter/index.module.scss
app/src/pages/MeetupsPage/index.js
app/src/pages/MentorshipPage/index.js

Ryan and I did pair programming and added social links to the footer. Please review.

Feat rc footer links

---

app/src/components/SingleArticle/index.js
app/src/containers/SingleArticleContainer/index.module.scss
package.json

The single article container will now parse any markdown

Feat: update single article container color and add markdown

---

app/src/pages/NotYetReadyPage/index.js

centered the button for the not yet ready page.
practicing little fixes with git ; )

fix: center button

---

app/src/containers/NotFoundContainer/index.js
app/src/containers/NotFoundContainer/messageData.js

Finally got around extracting the message data and putting it into a separate file.
I left it for now in the NotFoundContainer, so that it would remain its own little world that can be moved around.
However, considering that @kellim is also intending to use the original messages, I was wondering whether there could be a better place to store it?

fix: improve code structure of NotFoundContainer

---

app/src/components/MartinRulz/index.js

centered the lower-level heading in the not yet ready component too.
thanks for noticing, @kellim !

fix: center text for mobile view in not yet ready component

---

.all-contributorsrc

I updated my contributions to have bug and code.

docs: Update my contributions

---

webpack.config.babel.js

See: https://github.com/grommet/grommet/issues/1018

fix: Add .json to the resolve in webpack config

---

README.md

Add a "Deploy to Myrskyt" button to help people create a live version of the application (Not necessary pull request, however may benefit contributors).

Add "Deploy to Myrskyt" button

---

app/src/components/LostPasswordModal/index.js
app/src/components/LostPasswordModal/index.module.scss

* Only show the instructions for resetting password until you've successfully submitted an email address.
* Adjusted style because it looks better with spacing adjustments with less text being displayed for success.

Fix kb reset pw remove instructions if success fixes #141

---

app/src/components/AuthFormFooter/index.js

Fix: add space between text and link in auth form footer

---

app/src/components/App/index.js

Changed the breakpoint from 768 to 860 to fix items in navbar
overlapping each other at certain viewport widths. - fixes #143

fix: fix navbar overlapping issue- fixes #143

---

app/src/components/SingleArticleContent/README.md
app/src/components/SingleArticleContent/index.js
app/src/components/SingleArticleContent/index.module.scss

Fixed the headline overflow issue in issue #156 
Also updated the README for the SingleArticleContent as I was editing that component already.

Headline Overflow Issue

---

app/src/containers/AboutContainer/about.md
app/src/containers/AboutContainer/index.js
app/src/pages/AboutPage/contributorVoices.js

Some small updates that were still missing, and some that make it look a tiny bit better : )

fix: mb update style and content of About page

---

app/src/components/AppNavigation/README.md

@JamesIves : In response to your issue #159.
@RyanCCollins : You shared a template a while ago. Where is that?

Docs: fill in README for components/AppNavigation

---

app/src/pages/AboutPage/contributorVoices.js

Thanks @JamesIves and @James-Gallagher for your responses.
I'm currently just adding github links and github images, also I am not sure about what everyone was doing on the project, so please add the labels you want!
: )

Feat: mb add 2 new contributor voices. Yay
